name: fast_pass
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # https://pub.dev/packages/flutter_statusbarcolor 状态栏颜色
  flutter_statusbarcolor: any
  # https://pub.dev/packages/fluro 路由
  fluro: ^1.4.0
  # https://pub.dev/packages/flutter_swiper 幻灯
  flutter_swiper: ^1.1.6
  # https://pub.dev/packages/dio 网络请求
  dio: ^2.1.7
  # https://pub.dev/packages/intl 国际化
  intl: ^0.15.8
  # https://pub.dev/packages/simple_cache 本地储存
  simple_cache: ^0.0.3
  # https://pub.dev/packages/tip_dialog  Tip Dialog
  tip_dialog: ^2.0.0
  # https://pub.dev/packages/flutter_sequence_animation 串行动画
  flutter_sequence_animation: ^3.0.1
  # https://pub.dev/packages/vector_math 矢量动画的计算
  vector_math: ^2.0.8
  # https://pub.dev/packages/badges 徽章、标记[小红点]
  badges: ^1.0.3
  # https://pub.dev/packages/gradient_text 文字渐变
  gradient_text: ^1.0.2
  # https://pub.dev/packages/provider 状态管理
  provider: ^3.0.0
  # https://pub.dev/packages/flutter_form_builder 创建表单小部件所需的语法糖，并减少了构建表单、验证字段、对更改作出反应以及以映射形式收集表单值所需的样板
  flutter_form_builder: ^3.2.0
  # https://pub.dev/packages/flutter_screenutil 屏幕适配
  flutter_screenutil: ^0.5.2
  # https://pub.dev/packages/gradient_app_bar 渐变app bar
  gradient_app_bar: ^0.0.1
  # https://pub.dev/packages/cached_network_image  缓存网络图片
  cached_network_image: ^0.8.0
  # https://pub.dev/packages/flutter_slidable  滑动删除
  flutter_slidable: ^0.5.3
  # https://pub.dev/packages/flutter_easyrefresh  下拉刷新以及上拉加载
  flutter_easyrefresh: ^1.2.7
  # https://pub.dev/packages/fluttertoast 弹框
  fluttertoast: ^3.1.0
  # https://github.com/flutter/plugins/tree/master/packages/image_picker 图片选择器
  image_picker: ^0.6.0+4
  # https://pub.flutter-io.cn/packages/flutter_spinkit loading动画
  flutter_spinkit: "^3.1.0"
  # https://pub.dev/packages/image_cropper 图片裁剪
  image_cropper: 1.0.2
  #https://pub.dev/packages/image_picker_saver 保存图片到本地
  image_picker_saver: 0.3.0
  #https://pub.dev/packages/http image_picker_saver依赖http
  http: ^0.11.3+15
  #https://pub.dev/packages/underline_indicator 下划线指示器
  underline_indicator: ^0.0.2
  #https://pub.dev/packages/transparent_image  站位图片
  transparent_image: 1.0.0
  #  https://pub.dev/packages/flutter_inner_drawer 抽屉
  flutter_inner_drawer: "^0.3.0"
  #https://pub.dev/packages/city_pickers 城市选择
  city_pickers: ^0.1.27
  #https://pub.dev/packages/webview_flutter 网页
  webview_flutter: ^0.3.10+3
  #https://pub.dev/packages/jpush_flutter 极光推送
  jpush_flutter: 
    git: 
      url: https://github.com/CaiJingLong/jpush-flutter-plugin.git
      ref: 4d847f9b2150dc4fd1f8a7620d414d60f464fab7

  fake_alipay:
    git:
      url: https://github.com/v7lin/fake_alipay.git
  # dio 使用cookie依赖库
  cookie_jar: ^1.0.0
  #https://pub.dev/packages/janalytics#-readme-tab- 极光统计
  janalytics: ^0.0.3
#  #友盟统计
#  flutter_umeng_analytics: ^0.0.2
  #https://pub.dev/packages/package_info 获取app版本号
  package_info: ^0.4.0+6
  #http://pub.dartlang.org/packages/device_info 获取系统信息
  device_info: 0.4.0+2
#  #https://pub.dev/packages/sharesdk mob分享
#  sharesdk: ^1.1.3
  #https://pub.dev/packages/oktoast flutter 弹窗
  oktoast: ^2.2.0
  fluwx: ^1.0.4

  flutter_downloader: ^1.1.9
  url_launcher: ^5.1.2
  permission_handler: 3.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.assets
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
